config/routes.rb
CocoSearch::Application.routes.draw do
  
  resources :searches, only: [:index, :show, :new, :create]
  
  mount Resque::Server, :at => "/resque"
  
  root "searches#index"
  

end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  respond_to :html, :json

  def index
    @searches = Search.all
    respond_with @searches
  end

  def show
    @search = Search.find(params[:id])
    respond_with @search
  end

  def new
    @search = Search.new
    respond_with @search
  end

  def create
    @search = Search.new(search_params)
    Resque.enqueue(SearchRunner, @search.id) if @search.save
    respond_with @search
  end

private
  def search_params
    params.require(:search).permit(:grammar, :evaluation_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CocoSearch" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">CocoSearch</a>
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div> <!--/row-->
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/searches/index.html.erb
<h1>Searches</h1>

<% if @searches %>
  <ul>
  <% @searches.each do |search| %>
    <li><%= link_to "Search #{search.id}", search %></li>
  <% end %>
  </ul>

<% else %>
  No searches have been created yet.
<% end %>

<%= link_to "Create a new search", new_search_path, class: "btn btn-primary" %>

app/views/searches/new.html.erb
<h1>Create a new Search</h1>

<%= form_for @search do |f| -%>
  <fieldset>
    <div class="control-group">
      <%= f.label :grammar, class: "control-label" %>

      <div class="controls">
        <%= f.text_area :grammar, style: "width: 800px; height: 300px;" %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :evaluation_url, class: "control-label" %>
      
      <div class="controls">
        <%= f.text_field :evaluation_url %>
      </div>
    </div>
    
    <div class="control-group">
      <div class="controls">
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to "Cancel", searches_path, class: "btn" %>
      </div>
    </div>
  </fieldset>
<% end -%>

app/views/searches/show.html.erb
<h1>Search #<%=@search.id%></h1>

<h3>Grammar</h3>
<pre><code><%=@search.grammar%></code></pre>

<h3>Evaluation URL</h3>
<pre><code><%=@search.evaluation_url%></code></pre>

<%= link_to "View all searches", searches_path %>